name: Build & Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  release:
    types: [created]
    
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup CMake
        uses: lukka/get-cmake@latest
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Gammie
          path: build/Release/Gammie.exe
      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: build/Release/Gammie.exe
